# Generated by Django 5.1.3 on 2024-12-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('customized_wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('mark_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('leverage', models.IntegerField(default=75)),
                ('position_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('margin_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('liquidity_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
    ]
