# Generated by Django 5.1.3 on 2024-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='margin_balance',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='unrealized_pnl',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='realized_pnl',
            field=models.CharField(max_length=100),
        ),
    ]
