# Generated by Django 5.1.3 on 2024-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0003_remove_portfolio_customized_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='margin',
            new_name='initial_quantity',
        ),
        migrations.RemoveField(
            model_name='position',
            name='liquidity_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='margin_ratio',
        ),
        migrations.RemoveField(
            model_name='position',
            name='mark_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='realized_pnl',
        ),
        migrations.RemoveField(
            model_name='position',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='position',
            name='size',
        ),
        migrations.RemoveField(
            model_name='position',
            name='unrealized_pnl',
        ),
        migrations.AddField(
            model_name='position',
            name='fluctuation_frequency',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='fluctuation_max',
            field=models.DecimalField(decimal_places=6, default=41.76, max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='fluctuation_min',
            field=models.DecimalField(decimal_places=6, default=40.32, max_digits=20),
        ),
    ]
